import React, { useState, useEffect } from 'react'; 
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Plant from '../components/plant/Plant'

export default function Home() {
 
  const [ loadingPlants, setLoading ] = useState(false);
  const [ plantsArr, setPlantsArr ] = useState([]);

  const processData = ( arr ) => {
    setLoading(false);
    setPlantsArr(arr.data)
  }

  const fetchPlants = async () => {
    setLoading(true);
    const res = await fetch(`http://plant-tracker-app.test/api/plants`);
    const data = await res.json();
    processData(data);
  }

  useEffect(()=> {    
    fetchPlants();   
  },[]); 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>  */}
 
      {/* </main> */}
      <Plant plants={plantsArr} />
 

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
